spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wefit
    username: wefit_user
    password: 26owWLC0XoIN7KqS6S5PIZY0PS4Utoek
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  application:
    name: BancoGVM